{{ if .Values.serviceAccount.create }}
{{- $name := include "cxcloud-service.name" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
{{- if or .Values.serviceAccount.roleArn .Values.serviceAccount.annotations }}
  annotations:
  {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
